# Generated by Django 3.0.4 on 2020-06-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('Cosmetics', 'Cosmetics'), ('Digital', 'Digital'), ('Electronics', 'Electronics'), ('Bag', 'Bag'), ('Wallet', 'Wallet'), ('T-Shirt', 'T-Shirt'), ('Jeans', 'Jeans'), ('Wrist-Watch', 'Wrist Watch'), ('Belt', 'Belt'), ('Sunglass', 'Sunglass'), ('Shirt', 'Shirt'), ('Trouser', 'Trouser'), ('Shorts', 'Shorts'), ('Book', 'Book'), ('None', 'None')], default=None, max_length=20)),
                ('sub_category', models.CharField(choices=[('None', 'None')], default=None, max_length=10)),
                ('category_type', models.CharField(choices=[('None', 'None')], default=None, max_length=12)),
                ('usable_by', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids'), ('Boys', 'Boys'), ('Girls', 'Girls'), ('None', 'None')], default=None, max_length=6)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='products')),
                ('added_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
