# Generated by Django 3.0.4 on 2020-06-03 18:31

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ouruser',
            managers=[
                ('objects', shop.models.OurUserProfileManager()),
            ],
        ),
        migrations.AddField(
            model_name='ouruser',
            name='mobile_no',
            field=models.CharField(default=12345, max_length=50),
            preserve_default=False,
        ),
    ]
