# Generated by Django 3.0.4 on 2020-06-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200604_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouruser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
