# Generated by Django 3.0.4 on 2020-06-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200604_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_type',
            field=models.CharField(choices=[('Hair-Care', 'Hair Care'), ('Skin-Care', 'Skin Care'), ('Beauty-Care', 'Beauty Care'), ('Health-Care', 'Health Care'), ('Wireless', 'Wireless'), ('Wired', 'Wired'), ('SLR', 'SLR'), ('DSLR', 'DSLR'), ('None', 'None')], default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(choices=[('E-Book', 'E-Book'), ('Kindle-Edition', 'Kindle Edition'), ('Software', 'Software'), ('None', 'None'), ('Monitor', 'Monitor'), ('Mouse', 'Mouse'), ('Keyboard', 'Keyboard'), ('Headphone', 'Headphone'), ('Earphone', 'Earphone'), ('Laptop', 'Laptop'), ('TV', 'TV'), ('Pen-Drive', 'Pen Drive'), ('Router', 'Router'), ('AC', 'AC'), ('Tablets', 'Tablets'), ('Camera', 'Camera'), ('None', 'None')], default=None, max_length=15),
        ),
    ]
